### ISSUE TITLE
No Resolve aars files from https://artifactory.appodeal.com/appodeal

### ISSUE THREAD

**Issue by Lucasito** [appodeal/explorestack-hs-unity-plugin#7] opened 2022-06-07 10:13 UTC
Hello.
When I initialize, I get an error:
```
06-07 14:16:17.993 16601 16696 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.explorestack.hs.sdk.HSAppConfig
06-07 14:16:17.993 16601 16696 E Unity   : java.lang.ClassNotFoundException: com.explorestack.hs.sdk.HSAppConfig
06-07 14:16:17.993 16601 16696 E Unity   : 	at java.lang.Class.classForName(Native Method)
06-07 14:16:17.993 16601 16696 E Unity   : 	at java.lang.Class.forName(Class.java:454)
06-07 14:16:17.993 16601 16696 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
06-07 14:16:17.993 16601 16696 E Unity   : 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
06-07 14:16:17.993 16601 16696 E Unity   : 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
06-07 14:16:17.993 16601 16696 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-07 14:16:17.993 16601 16696 E Unity   : 	at android.os.Looper.loop(Looper.java:236)
06-07 14:16:17.993 16601 16696 E Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
06-07 14:16:17.993 16601 16696 E Unity   : Caused by: java.lang.ClassNotFoundException: com.explorestack.hs.sdk.HSAppConfig
06-07 14:16:17.993 16601 16696 E Unity   : 	... 8 more
06-07 14:16:17.993 16601 16696 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
06-07 14:16:17.993 16601 16696 E Unity   :   at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0 
06-07 14:16:17.993 16601 16696 E Unity   :   at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args)
```
APK don't have this class:
![image](https://user-images.githubusercontent.com/13868624/172354999-2e6e73c2-7ebf-43a2-b011-dab3f164ec70.png)

When I do force resolve, I can't see the repository for com.explorestack.hs artifact: sdk
![image](https://user-images.githubusercontent.com/13868624/172355543-d3f92a7a-a4f2-4215-90a8-4e7cd4026e08.png)

**Comment by dmitriifeshchenko** [comment] 2022-06-07 14:00
Hi, @Lucasito.

I'm not able to reproduce this behavior even on a newly created project.

![image](https://user-images.githubusercontent.com/43773640/172398002-5abe0da2-c161-47b5-abc3-11e997e2ad4f.png)

Unfortunately, there is not enough info to start the investigation. Could you please send us a minimal reproducible example?

**Comment by Lucasito** [comment] 2022-06-07 14:08
Hi, @DmitriiFeshchenko 
What version of Unity do you have? I build on 2021.3.3 (LTS)

**Comment by dmitriifeshchenko** [comment] 2022-06-07 14:11
@Lucasito, by accident, it's the same. But I do not think that the issue is related to the engine version. Most likely, it's because of the project settings.

![image](https://user-images.githubusercontent.com/43773640/172401423-8a1a43d1-86ff-4b4c-ac39-9cee47ff0d27.png)

**Comment by dmitriifeshchenko** [comment] 2022-06-15 11:18
I'm closing this issue for now as there are no updates.

**Closed as not planned by dmitriifeshchenko** 2022-06-15 11:18 UTC
